const CHECK_WALLET_CONNECTED = 'CHECK_WALLET_CONNECTED'
const CHECK_WALLET_CONNECTED_SUCCESS = 'CHECK_WALLET_CONNECTED_SUCCESS'
const CHECK_WALLET_CONNECTED_ERROR = 'CHECK_WALLET_CONNECTED_ERROR'

const CONNECT_WALLET = 'CONNECT_WALLET'
const CONNECT_WALLET_ERROR = 'CONNECT_WALLET_ERROR'
const CONNECT_WALLET_SUCCESS = 'CONNECT_WALLET_SUCCESS'

const MINT_PUNK = 'MINT_PUNK'
const MINT_PUNK_SUCCESS = 'MINT_PUNK_SUCCESS'
const MINT_PUNK_ERROR = 'MINT_PUNK_ERROR'

const GET_MINTED_PUNKS = 'GET_MINTED_PUNKS'
const GET_MINTED_PUNKS_SUCCESS = 'GET_MINTED_PUNKS_SUCCESS'

export {
  CHECK_WALLET_CONNECTED,
  CHECK_WALLET_CONNECTED_SUCCESS,
  CHECK_WALLET_CONNECTED_ERROR,
  CONNECT_WALLET,
  CONNECT_WALLET_ERROR,
  CONNECT_WALLET_SUCCESS,
  MINT_PUNK,
  MINT_PUNK_SUCCESS,
  MINT_PUNK_ERROR,
  GET_MINTED_PUNKS,
  GET_MINTED_PUNKS_SUCCESS,
}
