const CHECK_WALLET_CONNECTED = 'CHECK_WALLET_CONNECTED'
const CHECK_WALLET_CONNECTED_SUCCESS = 'CHECK_WALLET_CONNECTED_SUCCESS'
const CHECK_WALLET_CONNECTED_ERROR = 'CHECK_WALLET_CONNECTED_ERROR'

const CONNECT_WALLET = 'CONNECT_WALLET'
const CONNECT_WALLET_ERROR = 'CONNECT_WALLET_ERROR'
const CONNECT_WALLET_SUCCESS = 'CONNECT_WALLET_SUCCESS'

const GET_MINTED_PUNKS = 'GET_MINTED_PUNKS'

export {
  CHECK_WALLET_CONNECTED,
  CHECK_WALLET_CONNECTED_SUCCESS,
  CHECK_WALLET_CONNECTED_ERROR,
  CONNECT_WALLET,
  CONNECT_WALLET_ERROR,
  CONNECT_WALLET_SUCCESS,
  GET_MINTED_PUNKS,
}
